import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { HashLink } from "react-router-hash-link";
const Navbar = ({ logoSrc, logoAlt, menuItems }) => {
    const [theme, setTheme] = useState("default");
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const [isThemeMenuOpen, setIsThemeMenuOpen] = useState(false);
    useEffect(() => {
        document.body.setAttribute("data-theme", theme);
    }, [theme]);
    return (_jsx("section", { className: "z-50 fixed w-full navbar-right", style: { top: 0, left: 0, right: 0 }, children: _jsxs("nav", { className: "navbar bg-gradient-to-r justify-between items-center bg-base-100 p-4", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("img", { src: logoSrc, alt: logoAlt, style: { maxWidth: "70px", maxHeight: "70px" }, className: "img-fluid" }), _jsx("a", { href: "#", className: "text-xl font-bold text-current", children: "DatosLab" })] }), _jsx("div", { className: "flex-none md:hidden", children: _jsx("button", { onClick: () => setIsMenuOpen(!isMenuOpen), className: "btn btn-ghost", children: "\u2630" }) }), _jsx("div", { className: `flex-none ${isMenuOpen ? "block" : "hidden"} md:flex`, children: _jsx("ul", { className: `menu menu-horizontal px-2 space-x-2 ${isMenuOpen ? "absolute bg-base-100 shadow-lg mt-2 rounded-lg z-50" : ""}`, children: menuItems.map((item, index) => (_jsx("li", { className: "p-0", children: item === "Home" ? (_jsx(Link, { to: "/", className: "hover:text-gray-300 text-current px-2 py-1", children: item })) : item === "Equipo" || item === "Proyectos" ? (_jsx(Link, { to: `/${item.toLowerCase()}`, className: "hover:text-gray-300 text-current px-2 py-1", children: item })) : (_jsx(HashLink, { smooth: true, to: `/#${item.toLowerCase()}`, className: "hover:text-gray-300 text-current px-2 py-1", children: item })) }, index))) }) }), _jsx("div", { className: "navbar-right", children: _jsxs("div", { className: "navbar-end mr-auto dropdown dropdown-hover mb-1", onMouseEnter: () => setIsThemeMenuOpen(true), onMouseLeave: () => setIsThemeMenuOpen(false), children: [_jsxs("div", { tabIndex: 0, role: "button", className: "btn m-1 bg-gradient-to-r from-blue-500 to-indigo-500 text-white rounded-lg shadow-lg", onClick: () => setIsThemeMenuOpen(!isThemeMenuOpen), children: ["Temas", _jsx("svg", { width: "12px", height: "12px", className: "inline-block h-2 w-2 fill-current opacity-60 ml-2", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 2048 2048", children: _jsx("path", { d: "M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z" }) })] }), isThemeMenuOpen && (_jsx("ul", { className: "dropdown-content bg-base-300 rounded-lg z-[1] w-52 p-2 shadow-lg", children: ["default", "light", "night", "retro", "aqua"].map((themeOption) => (_jsx("li", { children: _jsxs("label", { className: "cursor-pointer flex items-center gap-2", children: [_jsx("input", { type: "radio", name: "theme-dropdown", className: "theme-controller", "aria-label": themeOption, value: themeOption, onChange: (e) => setTheme(e.target.value), checked: theme === themeOption }), _jsx("span", { className: "text-sm capitalize", children: themeOption })] }) }, themeOption))) }))] }) })] }) }));
};
export default Navbar;
